### ISSUE TITLE
Error when receiving message from tube.

### ISSUE THREAD

**Issue by cryptoqube777** [koodaamo/aiostalk#8] opened 2024-07-24 11:16 UTC
Hi
I'm using aiostalk to share messages  between two scripts.
Sometimes (pretty often) when fetching message from tube on consumer side, i receive the Assertion error when trying to execute the following line:
**assert data[-2:] == b \r\n**

All messages are the same, most of them are being passed fine, but this error arises pretty often.
Need some help on how to fix it, unless it's not a library bug. Library versions are as follows:
aiostalk==1.2
greenstalk==2.0.2

Python version is 3.12.4

**Comment by Tezar** [comment] 2024-09-10 15:24
Ok, had same problem, found the root cause, came to report and found your issue.

Problem is inherently in the greenstalk but it will need some patching in aiostalk too. When parsing response, the call is made for `self._reader.read(size + 2)` (+2 is for thr trailing \r\n). But the param is for bytes returned **at most** not exact. Issue is in the base greenstalk too, but I guess multiple aio operations put more stress on the socket  buffers.

Fixed code could look like this:

 ```
   async def _read_chunk(self, size: int) -> bytes:
        data = b''
        remaining = size + 2
        while remaining > 0:
            chunk = await self._reader.read(remaining)
            if not chunk:
                raise EOFError(f"End of file reached. Expected {size + 2} bytes, read {len(data)} bytes.")
            data += chunk
            remaining -= len(chunk)

        return _parse_chunk(data, size)
```

But the problem should be addressed in greenstalk too, which could break this version, hence no PR yet.

Will try to get in touch with author of greenstalk and see if he has any ideas/objection first. 
For time being this version is tested/working fine, having it in published in pip would save lot of headache though.

**Comment by Tezar** [comment] 2024-09-11 07:56
Nevermind, there is actually `readexactly` method on the reader. Made a PR #9 . In the mean time before this will get pushed to pip, you can use something like `pip install git+https://github.com/Tezar/aiostalk.git@master` to get patched version.

**Comment by petri** [comment] 2024-09-17 09:39
deployed 1.3

**Closed as completed by petri** 2024-09-17 09:39 UTC
